server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG
management.endpoint.health.show-components: always
management.endpoint.health.show-details: always
management.endpoints.health.sensitive: false